### PR TITLE
update

### PR DESCRIPTION
**Pull request by ClarenceRose**

### CODE REVIEW

**Review by ClarenceRose — COMMENTED** [review]
Changed the bracket

**Review by ClarenceRose — COMMENTED** [review]
approved

**Comment by claesmk** [comment]
Unit tests are failing because you need to update the [length](https://github.com/NCATComp410/comp410_fall_2022/blob/9315699fad9e7b6042bfd3b9270b7e12cd2af71e/test_pii_detect.py#L23) of the slogan list

You will also need to update your fork and resolve merge conflicts

**Review by ClarenceRose — COMMENTED** [review]
changes

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by ClarenceRose — COMMENTED** [review]
update

**Review by uvmoore — APPROVED** [review]

**Pull request merged**
