### PR TITLE
Added "Aggie PRIDE!" to slogan list

### PR DESCRIPTION
**Pull request by michaeltheedev**
Title

### CODE REVIEW

**Review by ClarenceRose — COMMENTED** [review]
Done

**Comment by claesmk** [comment]
You need to resolve the merge conflicts

**Comment by michaeltheedev** [comment]
> You need to resolve the merge conflicts

Merge conflicts resolved

**Review by claesmk — APPROVED** [review]
There is some duplication in the slogan list.  It looks like you were able to replace your slogan with one of the duplicates which is OK.

**Pull request merged**
